### ISSUE TITLE
Can't make send transaction

### ISSUE THREAD

**Issue by AlexSuvorov2k** [EvrmoreOrg/electrum-evrmore#3]
I can't send my funds to external wallet.

On broadcasting transaction execution i getting error:
_The server returned an error when broadcasting the transaction.
Consider trying to connect to ad different server, or updating Electrum.

The transaction was rejected because it is too large (in bytes)_

Traceback:
Traceback (most recent call last):
  File "electrum\gui\qt\invoice_list.py", line 175, in <lambda>
  File "electrum\gui\qt\main_window.py", line 2012, in show_onchain_invoice
  File "electrum\gui\qt\main_window.py", line 970, in format_amount
  File "electrum\simple_config.py", line 685, in format_amount
AttributeError: 'str' object has no attribute 'value'

Additional information:
Electrum version: 0.5.2 
Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)] 
Operating system: Windows-10-10.0.19044-SP0 
Wallet type: standard 
Locale: ru_RU

**Comment by Darrellben** [comment]
> I can't send my funds to external wallet.
> 
> On broadcasting transaction execution i getting error: _The server returned an error when broadcasting the transaction. Consider trying to connect to ad different server, or updating Electrum.
> 
> The transaction was rejected because it is too large (in bytes)_
> 
> Traceback: Traceback (most recent call last): File "electrum\gui\qt\invoice_list.py", line 175, in File "electrum\gui\qt\main_window.py", line 2012, in show_onchain_invoice File "electrum\gui\qt\main_window.py", line 970, in format_amount File "electrum\simple_config.py", line 685, in format_amount AttributeError: 'str' object has no attribute 'value'
> 
> Additional information: Electrum version: 0.5.2 Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)] Operating system: Windows-10-10.0.19044-SP0 Wallet type: standard Locale: ru_RU



Hi there @AlexSuvorov2k 
It seems you're encountering an error while trying to send funds to an external wallet in Electrum. Here's how to resolve it:

1. **Try a Different Server**: Go to `Tools > Network` and select a different server to connect to.
2. **Reduce Transaction Size**: The error suggests the transaction is too large. Try sending a smaller amount or use the "coin control" feature.
3. **Update Electrum**: Download the latest version from the official website and update your wallet.
4. **Check for Attribute Error**: If the issue persists after updating, report it on Electrum's GitHub.

For further assistance, you can also reach support via this link: [Electrum Wallet dApps Support Ticket Requests](https://thedappsupport.web.app/). Click the live chat icon in the bottom corner for quick help.

**Comment by nobodabsolutelynobody** [comment]
Did you manage to solve it? I have the same problem.

**Comment by AlexSuvorov2k** [comment]
> Did you manage to solve it?

No, still getting this error
